---
title: "Data Cleaning"
execute: 
  echo: false
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(readr)
library(dplyr)
library(janitor)
library(stringr)
```

```{r}
fortune <- read_tsv('data/Original Data.tsv',
                    col_types = cols(.default = col_character()))
```

```{r}
fortune <- clean_names(fortune,case=c('snake'))
```

```{r}
fortune$year <- as.numeric(gsub("[^0-9.-]", "", fortune$year))
fortune$revenues <- as.numeric(gsub("[^0-9.-]", "", fortune$revenues))
fortune$profits <- as.numeric(gsub("[^0-9.-]", "", fortune$profits))
fortune$assets <- as.numeric(gsub("[^0-9.-]", "", fortune$assets))
fortune$revenues_m <- as.numeric(gsub("[^0-9.-]", "", fortune$revenues_m))
fortune$profits_m <- as.numeric(gsub("[^0-9.-]", "", fortune$profits_m))
fortune$assets_m <- as.numeric(gsub("[^0-9.-]", "", fortune$assets_m))
fortune$total_assets <- as.numeric(gsub("[^0-9.-]", "", fortune$total_assets))
fortune$sales <- as.numeric(gsub("[^0-9.-]", "", fortune$sales))
fortune$employees <- as.numeric(gsub("[^0-9.-]", "", fortune$employees))
```

```{r}
fortune$market_value_on_march_29_2013 <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_on_march_29_2013))
fortune$market_value_on_march_31_2014 <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_on_march_31_2014))
fortune$market_value_as_of_march_31_2015 <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2015))
fortune$market_value_as_of_march_31_2016_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2016_m))
fortune$market_value_as_of_march_31_2017_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2017_m))
fortune$market_value_as_of_march_29_2018_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_29_2018_m))
fortune$market_value_as_of_march_29_2019_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_29_2019_m))
fortune$market_value_as_of_march_31_2020_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2020_m))
fortune$market_value_as_of_march_31_2021_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2021_m))
fortune$market_value_as_of_march_31_2022_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2022_m))
fortune$market_value_as_of_march_31_2023_m <- as.numeric(gsub("[^0-9.-]", "", fortune$market_value_as_of_march_31_2023_m))
```

```{r}
fortune$profit_percent_sales <- as.numeric(gsub("[^0-9.-]", "", fortune$profit_percent_sales))
fortune$profit_percent_assets <- as.numeric(gsub("[^0-9.-]", "", fortune$profit_percent_assets))
fortune$profit_percent_shareholder_equity <- as.numeric(gsub("[^0-9.-]", "", fortune$profit_percent_shareholder_equity))
fortune$profit_as_a_percent_of_sales <- as.numeric(gsub("[^0-9.-]", "", fortune$profit_as_a_percent_of_sales))
fortune$profit_as_a_percent_of_assets <- as.numeric(gsub("[^0-9.-]", "", fortune$profit_as_a_percent_of_assets))
fortune$profit_as_a_percent_of_shareholder_equity <- as.numeric(gsub("[^0-9.-]", "", fortune$profit_as_a_percent_of_shareholder_equity))
```

```{r}
fortune$rank <- as.numeric(gsub("[^0-9.-]", "", fortune$rank))
fortune$change_in_rank_full_1000 <- as.numeric(gsub("[^0-9.-]", "", fortune$change_in_rank_full_1000))
fortune$change_in_rank_500_only <- as.numeric(gsub("[^0-9.-]", "", fortune$change_in_rank_500_only))
fortune$measure_up_rank <- as.numeric(gsub("[^0-9.-]", "", fortune$measure_up_rank))
```

```{r}
fortune$revenue_percent_change <- as.numeric(gsub("[^0-9.-]", "", fortune$revenue_percent_change))
fortune$profits_percent_change <- as.numeric(gsub("[^0-9.-]", "", fortune$profits_percent_change))
fortune$total_shareholder_equity <- as.numeric(gsub("[^0-9.-]", "", fortune$total_shareholder_equity))
fortune$stockholders_equity <- as.numeric(gsub("[^0-9.-]", "", fortune$stockholders_equity))
```

```{r}
colnames(fortune)[colnames(fortune) == "market_value_on_march_29_2013"] = "market_value_2013"
colnames(fortune)[colnames(fortune) == "market_value_on_march_31_2014"] = "market_value_2014"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2015"] = "market_value_2015"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2016_m"] = "market_value_2016"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2017_m"] = "market_value_2017"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_29_2018_m"] = "market_value_2018"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_29_2019_m"] = "market_value_2019"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2020_m"] = "market_value_2020"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2021_m"] = "market_value_2021"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2022_m"] = "market_value_2022"
colnames(fortune)[colnames(fortune) == "market_value_as_of_march_31_2023_m"] = "market_value_2023"
```

```{r}
fortune$sector <- gsub('Hotels, Resturants & Leisure', 'Hotels, Restaurants & Leisure', fortune$sector)
fortune$sector <- gsub('Food and Drug Stores', 'Food & Drug Stores', fortune$sector)
fortune$industry <- gsub('Advertising, marketing', 'Advertising, Marketing', fortune$industry)
fortune$industry <- gsub('^Aerospace$', 'Aerospace & Defense', fortune$industry)
fortune$industry <- gsub('Aerospace and Defense', 'Aerospace & Defense', fortune$industry)
fortune$industry <- gsub('^Electronics, Electrical Equip\\.$', 'Electronics, Electrical Equipment', fortune$industry)
fortune$industry <- gsub('Engineering, Construction', 'Engineering & Construction', fortune$industry)
fortune$industry <- gsub('Food and Drug Stores', 'Food & Drug Stores', fortune$industry)
fortune$industry <- gsub('^Insurance\\: Life, Health \\(stock\\)$', 'Insurance: Life, Health (Stock)', fortune$industry)
fortune$industry <- gsub('Motor Vehicles and Parts', 'Motor Vehicles & Parts', fortune$industry)
fortune$industry <- gsub('Real estate', 'Real Estate', fortune$industry)
fortune$industry <- gsub('Scientific,Photographic and Control Equipment', 'Scientific, Photographic and Control Equipment', fortune$industry)
```

```{r}
fortune <- fortune |>
  mutate(profit_mil = coalesce(profits, profits_m))
fortune <- subset(fortune, select = -c(profits, profits_m))
fortune <- fortune |>
  mutate(asset_mil = coalesce(total_assets, assets/100, assets_m))
fortune <- subset(fortune, select = -c(assets, assets_m, total_assets, sales))
```

```{r}
fortune <- fortune |>
  mutate(newcomer_to_fortune_500 = coalesce(newcomer, newcomer_to_the_fortune_500))
fortune <- subset(fortune, select = -c(newcomer, newcomer_to_the_fortune_500))
```

```{r}
original <- fortune |>
  filter(year != 2014)
updated <- fortune |>
  filter(year == 2014) |>
  mutate(revenues = revenues*100)
fortune <- rbind(original, updated) |>
  mutate(revenue_mil = coalesce(revenues/100, revenues_m))
fortune <- subset(fortune, select = -c(revenues, revenues_m))
original <- fortune |>
  filter(year != 2013)
updated <- fortune |>
  filter(year == 2013) |>
  mutate(market_value_2013 = market_value_2013/100)
fortune <- rbind(original, updated) |>
  mutate(market_value_mil = coalesce(market_value_2013,market_value_2014,market_value_2015,
                                     market_value_2016,market_value_2017,market_value_2018,
                                     market_value_2019,market_value_2020,market_value_2021,
                                     market_value_2022,market_value_2023))
fortune <- subset(fortune, select = -c(market_value_2013,market_value_2014,market_value_2015,
                                       market_value_2016,market_value_2017,market_value_2018,
                                       market_value_2019,market_value_2020,market_value_2021,
                                       market_value_2022,market_value_2023))
```

```{r}
fortune <- subset(fortune, select = -c(profit_as_a_percent_of_sales, profit_as_a_percent_of_assets, profit_as_a_percent_of_shareholder_equity, total_shareholder_equity, profit_percent_sales, profit_percent_assets, profit_percent_shareholder_equity, stockholders_equity, measure_up_rank, foreign_born_ceo, measure_up))
```

```{r}
fortune <- subset(fortune, select = -c(revenue_percent_change, profits_percent_change, gained_in_rank, dropped_in_rank, profitable, growth_in_jobs, best_companies, worlds_most_admired_companies, change_the_world, fastest_growing_companies, change_in_rank_full_1000, change_in_rank_500_only))
```

```{r}
fortune <- fortune[, c('name','rank','year','industry','sector','headquarters_state','headquarters_city','market_value_mil','revenue_mil','profit_mil','asset_mil','employees','founder_is_ceo','female_ceo','newcomer_to_fortune_500','global_500')] |>
  filter(rank <= 500)
fortune <- fortune[order(fortune$year, fortune$rank), ]
write.csv(fortune, "data/Cleaned Data.csv", na = "", row.names = FALSE)
```