---
title: "Headquarter Locations"
execute: 
  echo: false
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(readr)
library(forcats)
```

```{r}
fortune <- read_csv('data/Cleaned Data.csv', show_col_types = FALSE) |>
  select(rank,name,headquarters_state,headquarters_city)
```

```{r}
state_hq <- fortune |>
  select(name, headquarters_state) |>
  unique() |>
  select(headquarters_state) |>
  drop_na() |>
  count(headquarters_state) |>
  mutate(headquarters_state = fct_reorder(headquarters_state, desc(n)))
```

```{r}
city_hq <- fortune |>
  select(name, headquarters_city) |>
  unique() |>
  select(headquarters_city) |>
  drop_na() |>
  count(headquarters_city) |>
  filter(n > 10) |>
  mutate(headquarters_city = fct_reorder(headquarters_city, desc(n)))
```

```{r}
state_hq |>
  ggplot(aes(x = headquarters_state, y = n)) +
  geom_bar(stat = 'identity', fill = '#0080ff') +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(title = "Location of Fortune 500 Companies' Headquarters",
       subtitle = "New York, California, Texas, and Illinois are the most common states.",
       x = 'Headquarter State Abbreviation',
       y = 'Count',
       caption = 'fortune.com') +
  theme_classic()
```

```{r}
city_hq |>
  ggplot(aes(x = headquarters_city, y = n)) +
  geom_bar(stat = 'identity', fill = '#0080ff') +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(title = "Location of Fortune 500 Companies' Headquarters",
       subtitle = "New York City, Houston, Atlanta, Dallas, and Chicago are the most common cities.",
       x = 'Headquarter City',
       y = 'Count',
       caption = 'fortune.com') +
  theme_classic()
```