---
title: "Sector and Industry"
execute: 
  echo: false
---

```{r}
#| message: false
#| warning: false
# Loading libraries
library(tidyverse)
library(readr)
library(forcats)
```

```{r}
# Reading data
fortune <- read_csv('data/Cleaned Data.csv', show_col_types = FALSE) |>
  select(rank, name, sector, industry)
```

```{r}
# Creating a dataframe
business_sect <- fortune |>
  select(name, sector) |>
  unique() |>
  select(sector) |>
  drop_na() |>
  count(sector) |>
  mutate(sector = fct_reorder(sector, n, .desc = FALSE))
```

```{r}
# Creating another dataframe
business_ind <- fortune |>
  select(name, industry) |>
  unique() |>
  select(industry) |>
  drop_na() |>
  count(industry) |>
  filter(n > 45) |>
  mutate(industry = fct_reorder(industry, n, .desc = FALSE))
```

```{r}
# Plotting business_sect dataframe
business_sect |>
  ggplot(aes(x = sector, y = n)) +
  geom_bar(stat = 'identity', fill = '#0080ff') +
  theme(axis.text.y = element_text(angle = 0)) +
  labs(title = "Business Sectors of Fortune 500 Companies",
       subtitle = "Financials, energy, technology, retailing, and health care are the most\ncommon sectors.",
       x = 'Sector',
       y = 'Count',
       caption = 'fortune.com') +
  coord_flip() +
  theme_classic()
```

```{r}
# Plotting business_ind dataframe
business_ind |>
  ggplot(aes(x = industry, y = n)) +
  geom_bar(stat = 'identity', fill = '#0080ff') +
  theme(axis.text.y = element_text(angle = 0)) +
  labs(title = "Industries of Fortune 500 Companies",
       subtitle = "Gas and electric utilities, commercial banks, specialty retailers, and\nproperty and casualty insurance are the most common industries.",
       x = 'Industry',
       y = 'Count',
       caption = 'fortune.com') +
  coord_flip() +
  theme_classic()
```